---
http_interactions:
- request:
    method: get
    uri: https://maps.googleapis.com/maps/api/geocode/json?sensor=false&address=94118&key=
    body:
      encoding: US-ASCII
      string: ''
    headers:
      accept:
      - ! '*/*'
      user-agent:
      - Ruby
  response:
    status:
      code: 200
      message: OK
    headers:
      content-type:
      - application/json; charset=UTF-8
      date:
      - Tue, 28 Jun 2016 16:02:58 GMT
      expires:
      - Wed, 29 Jun 2016 16:02:58 GMT
      cache-control:
      - public, max-age=86400
      access-control-allow-origin:
      - ! '*'
      server:
      - mafe
      x-xss-protection:
      - 1; mode=block
      x-frame-options:
      - SAMEORIGIN
      alternate-protocol:
      - 443:quic
      alt-svc:
      - quic=":443"; ma=2592000; v="34,33,32,31,30,29,28,27,26,25"
      accept-ranges:
      - none
      vary:
      - Accept-Language,Accept-Encoding
      transfer-encoding:
      - chunked
    body:
      encoding: US-ASCII
      string: ! "{\n   \"results\" : [\n      {\n         \"address_components\" :
        [\n            {\n               \"long_name\" : \"94118\",\n               \"short_name\"
        : \"94118\",\n               \"types\" : [ \"postal_code\" ]\n            },\n
        \           {\n               \"long_name\" : \"San Francisco\",\n               \"short_name\"
        : \"SF\",\n               \"types\" : [ \"locality\", \"political\" ]\n            },\n
        \           {\n               \"long_name\" : \"San Francisco County\",\n
        \              \"short_name\" : \"San Francisco County\",\n               \"types\"
        : [ \"administrative_area_level_2\", \"political\" ]\n            },\n            {\n
        \              \"long_name\" : \"California\",\n               \"short_name\"
        : \"CA\",\n               \"types\" : [ \"administrative_area_level_1\", \"political\"
        ]\n            },\n            {\n               \"long_name\" : \"United
        States\",\n               \"short_name\" : \"US\",\n               \"types\"
        : [ \"country\", \"political\" ]\n            }\n         ],\n         \"formatted_address\"
        : \"San Francisco, CA 94118, USA\",\n         \"geometry\" : {\n            \"bounds\"
        : {\n               \"northeast\" : {\n                  \"lat\" : 37.791637,\n
        \                 \"lng\" : -122.4436991\n               },\n               \"southwest\"
        : {\n                  \"lat\" : 37.766062,\n                  \"lng\" : -122.479504\n
        \              }\n            },\n            \"location\" : {\n               \"lat\"
        : 37.7822891,\n               \"lng\" : -122.463708\n            },\n            \"location_type\"
        : \"APPROXIMATE\",\n            \"viewport\" : {\n               \"northeast\"
        : {\n                  \"lat\" : 37.791637,\n                  \"lng\" : -122.4436991\n
        \              },\n               \"southwest\" : {\n                  \"lat\"
        : 37.766062,\n                  \"lng\" : -122.479504\n               }\n
        \           }\n         },\n         \"place_id\" : \"ChIJE8NGljiHhYARnSY8nSgLJkk\",\n
        \        \"types\" : [ \"postal_code\" ]\n      }\n   ],\n   \"status\" :
        \"OK\"\n}\n"
    http_version: '1.1'
  recorded_at: Tue, 28 Jun 2016 16:02:59 GMT
recorded_with: VCR 2.6.0
