shared: &shared
  app:
    canonical_url: "https://www.federalregister.gov"

  varnish:
    host: <%= ENV["VARNISH_ADDR"] || 'varnish' %>
    port: 6082
  regulations_dot_gov:
    base_uri: <%= ENV["REG_GOV_BASE_URL"] || 'http://api.data.gov/TEST/regulations/v3' %>
    throttle:
      at: <%= ENV["REG_GOV_JOBS_THROTTLE_AT"] || 2 %>
      per: <%= ENV["REG_GOV_JOBS_THROTTLE_PER"] || 5 %>
  public_inspection:
    import: false
  cron:
    google_analytics: true
    gpo_images: true
    import: true
    public_inspection: true
    sphinx: true
    regulations_dot_gov:
      comments: true
      dockets: true
      documents: true

  sphinx:
    enable_event_index: false
    enable_regulatory_plan_index: false
    use_local_pil_date: false

# Make any updates -web also
test:
  <<: *shared
  s3_buckets:
    zipped_eps_images: XXXXXXXXXXXXXXXXXXXXXXX

development:
  <<: *shared
  app:
    canonical_url: "https://dev-fr2.criticaljuncture.org"
  s3_buckets:
    zipped_eps_images: eps.images.fr2.local
    private_images: private.images.fr2.local
    public_images: images.fr2.local
    lede_photos: lede-photos.fr2.local
    agency_logos: agency-logos.fr2.local
    public_inspection: public-inspection.fr2.local
  ofr_flickr_group_id: 1058319@N21
  cron:
    google_analytics: false
    gpo_images: false
    import: false
    public_inspection: false
    sphinx: true
    regulations_dot_gov:
      comments: false
      dockets: false
      documents: false
    varnish: false

staging:
  <<: *shared
  app:
    canonical_url: "https://fr2.criticaljuncture.org"
  s3_buckets:
    zipped_eps_images: eps.images.fr2.criticaljuncture.org
    private_images: private.images.fr2.criticaljuncture.org
    public_images: images.fr2.criticaljuncture.org
    lede_photos: lede-photos.fr2.criticaljuncture.org
    agency_logos: agency-logos.fr2.criticaljuncture.org
    public_inspection: public-inspection.fr2.criticaljuncture.org
  ofr_flickr_group_id: 1058319@N21
  public_inspection:
    import: true

production:
  <<: *shared
  s3_buckets:
    zipped_eps_images: eps.images.federalregister.gov
    private_images: private.images.federalregister.gov
    public_images: images.federalregister.gov
    lede_photos: lede-photos.federalregister.gov
    agency_logos: agency-logos.federalregister.gov
    public_inspection: public-inspection.federalregister.gov
  ofr_flickr_group_id: 1058319@N21
  public_inspection:
    import: true
  regulations_dot_gov:
    base_uri: <%= ENV["REG_GOV_BASE_URL"] || 'http://api.data.gov/regulations/v3' %>
    throttle:
      at: <%= ENV["REG_GOV_JOBS_THROTTLE_AT"] || 2 %>
      per: <%= ENV["REG_GOV_JOBS_THROTTLE_PER"] || 5 %>
