shared: &shared
  varnish:
    host: <%= ENV["VARNISH_ADDR"] || 'varnish' %>
    port: 6082
  regulations_dot_gov:
    base_uri: <%= ENV["REG_GOV_BASE_URL"] || 'http://api.data.gov/TEST/regulations/v3' %>

# Make any updates -web also
test:
  <<: *shared
  s3_buckets:
    zipped_eps_images: XXXXXXXXXXXXXXXXXXXXXXX

development:
  <<: *shared
  s3_buckets:
    zipped_eps_images: eps.images.federalregister.gov
    private_images: private.images.fr2.local
    public_images: images.fr2.local
  ofr_flickr_group_id: 1058319@N21

staging:
  <<: *shared
  s3_buckets:
    zipped_eps_images: eps.images.federalregister.gov
    private_images: private.images.fr2.criticaljuncture.org
    public_images: images.fr2.criticaljuncture.org
  ofr_flickr_group_id: 1058319@N21

production:
  <<: *shared
  s3_buckets:
    zipped_eps_images: eps.images.federalregister.gov
    private_images: private.images.federalregister.gov
    public_images: images.federalregister.gov
  ofr_flickr_group_id: 1058319@N21
  regulations_dot_gov:
    base_uri: <%= ENV["REG_GOV_BASE_URL"] || 'http://api.data.gov/regulations/v3' %>
