shared: &shared
  address: <%= 'localhost' || ENV["SPHINX_PORT_3312_TCP_ADDR"] || 'sphinx' %>
  compat_sphinxql_magics: 0
  config_file: config/sphinx/sphinx.conf
  pid_file: pids/searchd.pid
  searchd_file_path: db/sphinx/
  index_exact_words: 1
  max_matches: 10000
  mem_limit: 528M
  morphology: stem_en
  # port: <%= ENV["SPHINX_PORT_3312_TCP_PORT"] || 3312 %>
  version: '2.1.2'
  max_children: 30
  mysql41: <%= ENV["SPHINX_PORT_3312_TCP_PORT"] || 3312 %>

development:
  <<: *shared

test:
  <<: *shared
  config_file: config/sphinx/test.sphinx.conf
  sql_range_step: 10000000

staging:
  <<: *shared

production:
  <<: *shared
